In [42]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import warnings
warnings.filterwarnings('ignore')

digits = load_digits()
dir(digits)

['DESCR', 'data', 'images', 'target', 'target_names']

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [44]:
lr = LogisticRegression()
lr.fit(x_train,y_train)
lr.score(x_test,y_test)

0.9629629629629629

In [45]:
svc = SVC()
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.3148148148148148

In [46]:
rf = RandomForestClassifier()
rf.fit(x_train,y_train)
rf.score(x_test,y_test)

0.9537037037037037

In [84]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5)
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [48]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index , test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [49]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)
    

In [70]:
from sklearn.model_selection import StratifiedKFold #better than KFold
skf = StratifiedKFold(n_splits = 10) 
    

In [71]:
from sklearn.datasets import load_digits
digits = load_digits()

In [72]:
score_l =[]
score_s = []
score_rf = []

for train_index,test_index in skf.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index], \
                                    digits.target[train_index],digits.target[test_index]
    score_l.append(get_score(LogisticRegression(),x_train,x_test,y_train,y_test))
    score_s.append(get_score(SVC(),x_train,x_test,y_train,y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators = 50),x_train,x_test,y_train,y_test))

In [73]:
score_l

[0.9081081081081082,
 0.9508196721311475,
 0.8950276243093923,
 0.9111111111111111,
 0.9497206703910615,
 0.9664804469273743,
 0.9776536312849162,
 0.949438202247191,
 0.8587570621468926,
 0.9431818181818182]

In [74]:
score_s

[0.4486486486486487,
 0.5846994535519126,
 0.3812154696132597,
 0.43333333333333335,
 0.4748603351955307,
 0.4301675977653631,
 0.5195530726256983,
 0.5898876404494382,
 0.5649717514124294,
 0.4431818181818182]

In [75]:
score_rf

[0.9351351351351351,
 0.9672131147540983,
 0.9613259668508287,
 0.9388888888888889,
 0.9441340782122905,
 0.9664804469273743,
 0.9832402234636871,
 0.9662921348314607,
 0.9322033898305084,
 0.9318181818181818]

In [85]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(),digits.data,digits.target)

array([0.89534884, 0.94991653, 0.90939597])

In [87]:
cross_val_score(SVC(kernel="linear"),digits.data,digits.target)

array([0.93521595, 0.95826377, 0.93791946])